apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: "swjfberd/reservation:05"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 20  # 초기화 시간을 충분히 확보
            timeoutSeconds: 3        # 응답 시간 확보
            periodSeconds: 10        # 체크 간격 조정
            failureThreshold: 5      # 연속 실패 허용 범위 축소
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 180 # 애플리케이션 완전 초기화 시간 확보
            timeoutSeconds: 5        # Liveness 응답 허용 시간 증가
            periodSeconds: 20        # 체크 주기 확대
            failureThreshold: 3      # 연속 실패 허용 범위 축소
